
CREATE TABLE ALCALDIA.PAIS (
    ID_PAIS NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR2(50) NOT NULL,
    CONSTRAINT PAIS_PK PRIMARY KEY (ID_PAIS)
);

CREATE TABLE ALCALDIA.PLANTEL_EDUCATIVO (
    ID_PLANTEL_EDUCATIVO NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR2(50) NOT NULL,
    LOCALIDAD VARCHAR2(50) NOT NULL,
    CONSTRAINT PLANTEL_EDUCATIVO_PK PRIMARY KEY (ID_PLANTEL_EDUCATIVO)
);

CREATE TABLE ALCALDIA.EMPRESA (
    ID_EMPRESA NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR2(50) NOT NULL,
    LOCALIDAD VARCHAR2(50) NOT NULL,
    CONSTRAINT EMPRESA_PK PRIMARY KEY (ID_EMPRESA)
);

CREATE TABLE ALCALDIA.ALCALDE (
    ID_ALCALDE NUMBER GENERATED ALWAYS AS IDENTITY,
    PRIMER_NOMBRE VARCHAR2(25) NOT NULL,
    SEGUNDO_NOMBRE VARCHAR2(25),
    PRIMER_APELLIDO VARCHAR2(25) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR2(25),
    CONSTRAINT ALCALDE_PK PRIMARY KEY (ID_ALCALDE)
);

CREATE TABLE ALCALDIA.ESTADO_DOCUMENTO (
    ID_ESTADO_DOCUMENTO NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR2(45) NOT NULL,
    CONSTRAINT ESTADO_DOCUMENTO_PK PRIMARY KEY (ID_ESTADO_DOCUMENTO)
);


CREATE TABLE ALCALDIA.GUARDERIA (
    ID_GUARDERIA NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR2(50) NOT NULL,
    LOCALIDAD VARCHAR2(50) NOT NULL,
    CONSTRAINT GUARDERIA_PK PRIMARY KEY (ID_GUARDERIA)
);


CREATE TABLE ALCALDIA.AREA (
    ID_AREA NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR2(50) NOT NULL,
    CONSTRAINT AREA_PK PRIMARY KEY (ID_AREA)
);


CREATE TABLE ALCALDIA.CIUDAD (
    ID_CIUDAD NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_PAIS NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    CONSTRAINT CIUDAD_PK PRIMARY KEY (ID_CIUDAD)
);


CREATE TABLE ALCALDIA.JORNADA (
    ID_JORNADA NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR2(50) NOT NULL,
    CONSTRAINT JORNADA_PK PRIMARY KEY (ID_JORNADA)
);


CREATE TABLE ALCALDIA.MODALIDAD (
    ID_MODALIDAD NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR2(50) NOT NULL,
    CONSTRAINT MODALIDAD_PK PRIMARY KEY (ID_MODALIDAD)
);


CREATE TABLE ALCALDIA.CARGO (
    ID_CARGO NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR2(50),
    CONSTRAINT CARGO_PK PRIMARY KEY (ID_CARGO)
);


CREATE TABLE ALCALDIA.TIPO_INFRAESTRUCTURA (
    ID_TIPO_INFRAESTRUCTURA NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR2(100) NOT NULL,
    CONSTRAINT TIPO_INFRAESTRUCTURA_PK PRIMARY KEY (ID_TIPO_INFRAESTRUCTURA)
);


CREATE TABLE ALCALDIA.TIPO_IDENTIFICACION (
    ID_TIPO_IDENTIFICACION NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR2(50) NOT NULL,
    CONSTRAINT TIPO_IDENTIFICACION_PK PRIMARY KEY (ID_TIPO_IDENTIFICACION)
);


CREATE TABLE ALCALDIA.TIPO_HABITACION (
    ID_TIPO_HABITACION NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR2(50),
    CONSTRAINT TIPO_HABITACION_PK PRIMARY KEY (ID_TIPO_HABITACION)
);


CREATE TABLE ALCALDIA.RUTA (
    ID_RUTA NUMBER GENERATED ALWAYS AS IDENTITY,
    DESCRIPCION VARCHAR2(50) NOT NULL,
    CONSTRAINT RUTA_PK PRIMARY KEY (ID_RUTA)
);


CREATE TABLE ALCALDIA.ENFERMEDAD (
    ID_ENFERMEDAD NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR2(50) NOT NULL,
    ESTADO NUMBER,
    CONSTRAINT ENFERMEDAD_PK PRIMARY KEY (ID_ENFERMEDAD)
);


CREATE TABLE ALCALDIA.TIPO_PLANTEL (
    ID_TIPO_PLANTEL NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR2(50) NOT NULL,
    CONSTRAINT TIPO_PLANTEL_PK PRIMARY KEY (ID_TIPO_PLANTEL)
);


CREATE TABLE ALCALDIA.ALCALDIA (
    ID_ALCALDIA NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_ALCALDE NUMBER NOT NULL,
    NOMBRE VARCHAR2(50),
    CONSTRAINT ALCALDIA_PK PRIMARY KEY (ID_ALCALDIA)
);


CREATE TABLE ALCALDIA.LOCALIDAD (
    ID_LOCALIDAD NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_ALCALDIA NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    CONSTRAINT LOCALIDAD_PK PRIMARY KEY (ID_LOCALIDAD)
);


CREATE TABLE ALCALDIA.BARRIO (
    ID_BARRIO NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_LOCALIDAD NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    AREA VARCHAR2(100) NOT NULL,
    ESTRATO NUMBER,
    CONSTRAINT BARRIO_PK PRIMARY KEY (ID_BARRIO)
);


CREATE TABLE ALCALDIA.BARRIO_RUTA (
    ID_BARRIO_RUTA NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_BARRIO NUMBER NOT NULL,
    ID_RUTA NUMBER NOT NULL,
    CONSTRAINT BARRIO_RUTA_PK PRIMARY KEY (ID_BARRIO_RUTA)
);


CREATE INDEX ALCALDIA.FK_BARRIO_RUTA_BARRIO_IDX
 ON ALCALDIA.BARRIO_RUTA
 ( ID_BARRIO ASC );

CREATE INDEX ALCALDIA.FK_BARRIO_RUTA_RUTA_IDX
 ON ALCALDIA.BARRIO_RUTA
 ( ID_RUTA ASC );

CREATE TABLE ALCALDIA.FAMILIA (
    ID_FAMILIA NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_BARRIO NUMBER NOT NULL,
    ID_TIPO_HABITACION NUMBER NOT NULL,
    NOMBRE VARCHAR2(5) NOT NULL,
    DIRECCION VARCHAR2(150) NOT NULL,
    TELEFONO VARCHAR2(20) NOT NULL,
    INGRESO NUMBER(15,2) NOT NULL,
    CONSTRAINT FAMILIA_PK PRIMARY KEY (ID_FAMILIA)
);


CREATE TABLE ALCALDIA.INTEGRANTE (
    ID_INTEGRANTE NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_TIPO_IDENTIFICACION NUMBER NOT NULL,
    ID_CIUDAD NUMBER NOT NULL,
    ID_FAMILIA NUMBER NOT NULL,
    IDENTIFICACION NUMBER NOT NULL,
    PRIMER_NOMBRE VARCHAR2(25) NOT NULL,
    SEGUNDO_NOMBRE VARCHAR2(25),
    PRIMERO_APELLIDO VARCHAR2(25) NOT NULL,
    SEGUNDO_APELIDO VARCHAR2(25),
    FECHA_NACIMIENTO DATE NOT NULL,
    CONSTRAINT INTEGRANTE_PK PRIMARY KEY (ID_INTEGRANTE)
);


CREATE TABLE ALCALDIA.ENFERMEDAD_INTEGRANTE (
    ID_ENFERMEDAD_INTEGRANTE NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_ENFERMEDAD NUMBER NOT NULL,
    ID_INTEGRANTE NUMBER NOT NULL,
    FECHA DATE,
    CONSTRAINT ENFERMEDAD_INTEGRANTE_PK PRIMARY KEY (ID_ENFERMEDAD_INTEGRANTE)
);


CREATE INDEX ALCALDIA.FK_ENFERMEDAD_INTEGRANTE_ENFERMEDAD_IDX
 ON ALCALDIA.ENFERMEDAD_INTEGRANTE
 ( ID_ENFERMEDAD ASC );

CREATE INDEX ALCALDIA.FK_ENFERMEDAD_INTEGRANTE_INTEGRANTE_IDX
 ON ALCALDIA.ENFERMEDAD_INTEGRANTE
 ( ID_INTEGRANTE ASC );

CREATE TABLE ALCALDIA.INTEGRANTE_EMPRESA (
    ID_INTEGRANTE_EMPRESA NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_EMPRESA NUMBER NOT NULL,
    ID_CARGO NUMBER NOT NULL,
    ID_INTEGRANTE NUMBER NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    ESTADO NUMBER,
    SUELDO NUMBER,
    CONSTRAINT INTEGRANTE_EMPRESA_PK PRIMARY KEY (ID_INTEGRANTE_EMPRESA)
);


CREATE INDEX ALCALDIA.FK_INT_EMPRESA_CARGO_IDX
 ON ALCALDIA.INTEGRANTE_EMPRESA
 ( ID_CARGO ASC );

CREATE INDEX ALCALDIA.FK_INT_EMPRESA_EMPRESA_IDX
 ON ALCALDIA.INTEGRANTE_EMPRESA
 ( ID_EMPRESA ASC );

CREATE INDEX ALCALDIA.FK_INT_EMPRESA_INTEGRANTE_IDX
 ON ALCALDIA.INTEGRANTE_EMPRESA
 ( ID_INTEGRANTE ASC );

CREATE TABLE ALCALDIA.GUARDERIA_INTEGRANTE (
    ID_GUARDERIA_INTEGRANTE NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_GUARDERIA NUMBER NOT NULL,
    ID_INTEGRANTE NUMBER NOT NULL,
    FECHA DATE,
    CONSTRAINT GUARDERIA_INTEGRANTE_PK PRIMARY KEY (ID_GUARDERIA_INTEGRANTE)
);


CREATE INDEX ALCALDIA.FK_GUARDERIA_INTEGRANTE_GUARDERIAS_IDX
 ON ALCALDIA.GUARDERIA_INTEGRANTE
 ( ID_GUARDERIA ASC );

CREATE INDEX ALCALDIA.FK_GUARDERIA_INTEGRANTE_INTEGRANTE_IDX
 ON ALCALDIA.GUARDERIA_INTEGRANTE
 ( ID_INTEGRANTE ASC );

CREATE TABLE ALCALDIA.ESCOLARIDAD (
    ID_ESCOLARIDAD NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_JORNADA NUMBER NOT NULL,
    ID_PLANTEL_EDUCATIVO NUMBER NOT NULL,
    ID_MODALIDAD NUMBER NOT NULL,
    ID_INTEGRANTE NUMBER NOT NULL,
    FECHA DATE NOT NULL,
    CONSTRAINT ESCOLARIDAD_PK PRIMARY KEY (ID_ESCOLARIDAD)
);


CREATE INDEX ALCALDIA.FK_ESCOLARIDAD_INTEGRANTE_IDX
 ON ALCALDIA.ESCOLARIDAD
 ( ID_INTEGRANTE ASC );

CREATE INDEX ALCALDIA.FK_ESCOLARIDAD_JORNADA_IDX
 ON ALCALDIA.ESCOLARIDAD
 ( ID_JORNADA ASC );

CREATE INDEX ALCALDIA.FK_ESCOLARIDAD_MODALIDAD_IDX
 ON ALCALDIA.ESCOLARIDAD
 ( ID_MODALIDAD ASC );

CREATE INDEX ALCALDIA.FK_ESCOLARIDAD_PLANTEL_EDUCATIVO_IDX
 ON ALCALDIA.ESCOLARIDAD
 ( ID_PLANTEL_EDUCATIVO ASC );

CREATE TABLE ALCALDIA.PLANTEL (
    ID_PLANTEL NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_TIPO_PLANTEL NUMBER NOT NULL,
    ID_LOCALIDAD NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    CONSTRAINT PLANTEL_PK PRIMARY KEY (ID_PLANTEL)
);


CREATE TABLE ALCALDIA.DEPENDENCIA (
    ID_DEPENCIA NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_ALCALDIA NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    CONSTRAINT DEPENDENCIA_PK PRIMARY KEY (ID_DEPENCIA)
);


CREATE TABLE ALCALDIA.AREA_DEPENDENCIA (
    ID_AREA_DEPENDENCIA NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_AREA NUMBER NOT NULL,
    ID_DEPENCIA NUMBER NOT NULL,
    CONSTRAINT AREA_DEPENDENCIA_PK PRIMARY KEY (ID_AREA_DEPENDENCIA)
);


CREATE INDEX ALCALDIA.FK_AREA_DEPENDENCIA_AREA_IDX
 ON ALCALDIA.AREA_DEPENDENCIA
 ( ID_AREA ASC );

CREATE INDEX ALCALDIA.FK_AREA_DEPENDENCIA_DEPENDENCIA_IDX
 ON ALCALDIA.AREA_DEPENDENCIA
 ( ID_DEPENCIA ASC );

CREATE TABLE ALCALDIA.INFRAESTRUCTURA (
    ID_INFRAESTRUCTURA NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_AREA_DEPENDENCIA NUMBER NOT NULL,
    ID_TIPO_INFRAESTRUCTURA NUMBER NOT NULL,
    NOMBRE VARCHAR2(50),
    ESPECIFICACIONES VARCHAR2(500),
    CODIGO NUMBER,
    CONSTRAINT INFRAESTRUCTURA_PK PRIMARY KEY (ID_INFRAESTRUCTURA)
);


CREATE TABLE ALCALDIA.EMPLEADO (
    ID_EMPLEADO NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_AREA_DEPENDENCIA NUMBER NOT NULL,
    PRIMERNOMBRE VARCHAR2(25) NOT NULL,
    SEGUNDONOMBRE VARCHAR2(25),
    PRIMERAPELLIDO VARCHAR2(25) NOT NULL,
    SEGUNDOAPELLIDO VARCHAR2(25),
    TELEFONO VARCHAR2(20) NOT NULL,
    DIRECCION VARCHAR2(150) NOT NULL,
    EMAIL VARCHAR2(150) NOT NULL,
    CONSTRAINT EMPLEADO_PK PRIMARY KEY (ID_EMPLEADO)
);


CREATE TABLE ALCALDIA.DOCUMENTO (
    ID_DOCUMENTO NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_ESTADO_DOCUMENTO NUMBER NOT NULL,
    ID_DEPENCIA NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(200),
    RUTA VARCHAR2(500) NOT NULL,
    CONSTRAINT DOCUMENTO_PK PRIMARY KEY (ID_DOCUMENTO)
);


CREATE INDEX ALCALDIA.FK_DOCUMENTO_DEPENDENCIA_IDX
 ON ALCALDIA.DOCUMENTO
 ( ID_DEPENCIA ASC );

CREATE INDEX ALCALDIA.FK_DOCUMENTO_ESTADO_DOCUMENTO_IDX
 ON ALCALDIA.DOCUMENTO
 ( ID_ESTADO_DOCUMENTO ASC );

ALTER TABLE ALCALDIA.CIUDAD ADD CONSTRAINT FK_CIUDAD_PAIS
FOREIGN KEY (ID_PAIS)
REFERENCES ALCALDIA.PAIS (ID_PAIS)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.ESCOLARIDAD ADD CONSTRAINT FK_JOVEN_PLANTEL_EDUCATIVO
FOREIGN KEY (ID_PLANTEL_EDUCATIVO)
REFERENCES ALCALDIA.PLANTEL_EDUCATIVO (ID_PLANTEL_EDUCATIVO)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.INTEGRANTE_EMPRESA ADD CONSTRAINT FK_ADULTO_EMPRESA
FOREIGN KEY (ID_EMPRESA)
REFERENCES ALCALDIA.EMPRESA (ID_EMPRESA)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.ALCALDIA ADD CONSTRAINT FK_ALCALDIA_ALCALDE
FOREIGN KEY (ID_ALCALDE)
REFERENCES ALCALDIA.ALCALDE (ID_ALCALDE)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.DOCUMENTO ADD CONSTRAINT FK_DOCUMENTO_ESTADO_DOCUMENTO
FOREIGN KEY (ID_ESTADO_DOCUMENTO)
REFERENCES ALCALDIA.ESTADO_DOCUMENTO (ID_ESTADO_DOCUMENTO)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.GUARDERIA_INTEGRANTE ADD CONSTRAINT FK_GUARDERIA_INTEGRANTES_GUARDERIA
FOREIGN KEY (ID_GUARDERIA)
REFERENCES ALCALDIA.GUARDERIA (ID_GUARDERIA)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.AREA_DEPENDENCIA ADD CONSTRAINT FK_AREA_DEPENDENCIA_AREA
FOREIGN KEY (ID_AREA)
REFERENCES ALCALDIA.AREA (ID_AREA)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.INTEGRANTE ADD CONSTRAINT FK_INTEGRANTE_CIUDAD
FOREIGN KEY (ID_CIUDAD)
REFERENCES ALCALDIA.CIUDAD (ID_CIUDAD)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.ESCOLARIDAD ADD CONSTRAINT FK_JOVEN_JORNADA
FOREIGN KEY (ID_JORNADA)
REFERENCES ALCALDIA.JORNADA (ID_JORNADA)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.ESCOLARIDAD ADD CONSTRAINT FK_JOVEN_MODALIDAD
FOREIGN KEY (ID_MODALIDAD)
REFERENCES ALCALDIA.MODALIDAD (ID_MODALIDAD)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.INTEGRANTE_EMPRESA ADD CONSTRAINT FK_ADULTO_CARGO
FOREIGN KEY (ID_CARGO)
REFERENCES ALCALDIA.CARGO (ID_CARGO)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.INFRAESTRUCTURA ADD CONSTRAINT FK_INFRAESTRUCTURA_TIPO_INFRAESTRUCTURA
FOREIGN KEY (ID_TIPO_INFRAESTRUCTURA)
REFERENCES ALCALDIA.TIPO_INFRAESTRUCTURA (ID_TIPO_INFRAESTRUCTURA)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.INTEGRANTE ADD CONSTRAINT FK_INTEGRANTE_TIPO_IDENTIFICACION
FOREIGN KEY (ID_TIPO_IDENTIFICACION)
REFERENCES ALCALDIA.TIPO_IDENTIFICACION (ID_TIPO_IDENTIFICACION)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.FAMILIA ADD CONSTRAINT FK_FAMILIA_TIPO_HABITACION
FOREIGN KEY (ID_TIPO_HABITACION)
REFERENCES ALCALDIA.TIPO_HABITACION (ID_TIPO_HABITACION)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.BARRIO_RUTA ADD CONSTRAINT FK_TRANSPORTE_TIPO_TRANSPORTE
FOREIGN KEY (ID_RUTA)
REFERENCES ALCALDIA.RUTA (ID_RUTA)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.ENFERMEDAD_INTEGRANTE ADD CONSTRAINT FK_ENFERMEDAD_INTEGRANTE_ENFERMEDAD
FOREIGN KEY (ID_ENFERMEDAD)
REFERENCES ALCALDIA.ENFERMEDAD (ID_ENFERMEDAD)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.PLANTEL ADD CONSTRAINT FK_PLANTEL_TIPO_PLANTEL
FOREIGN KEY (ID_TIPO_PLANTEL)
REFERENCES ALCALDIA.TIPO_PLANTEL (ID_TIPO_PLANTEL)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.DEPENDENCIA ADD CONSTRAINT FK_DEPENDENCIA_ALCALDIA
FOREIGN KEY (ID_ALCALDIA)
REFERENCES ALCALDIA.ALCALDIA (ID_ALCALDIA)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.LOCALIDAD ADD CONSTRAINT FK_LOCALIDAD_ALCALDIA
FOREIGN KEY (ID_ALCALDIA)
REFERENCES ALCALDIA.ALCALDIA (ID_ALCALDIA)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.PLANTEL ADD CONSTRAINT FK_PLANTEL_LOCALIDAD
FOREIGN KEY (ID_LOCALIDAD)
REFERENCES ALCALDIA.LOCALIDAD (ID_LOCALIDAD)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.BARRIO ADD CONSTRAINT FK_BARRIO_LOCALIDAD
FOREIGN KEY (ID_LOCALIDAD)
REFERENCES ALCALDIA.LOCALIDAD (ID_LOCALIDAD)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.FAMILIA ADD CONSTRAINT FK_FAMILIA_BARRIO
FOREIGN KEY (ID_BARRIO)
REFERENCES ALCALDIA.BARRIO (ID_BARRIO)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.BARRIO_RUTA ADD CONSTRAINT FK_TRANSPORTE_BARRIO
FOREIGN KEY (ID_BARRIO)
REFERENCES ALCALDIA.BARRIO (ID_BARRIO)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.INTEGRANTE ADD CONSTRAINT FK_INTEGRANTE_FAMILIA
FOREIGN KEY (ID_FAMILIA)
REFERENCES ALCALDIA.FAMILIA (ID_FAMILIA)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.ESCOLARIDAD ADD CONSTRAINT FK_JOVEN_INTEGRANTE
FOREIGN KEY (ID_INTEGRANTE)
REFERENCES ALCALDIA.INTEGRANTE (ID_INTEGRANTE)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.GUARDERIA_INTEGRANTE ADD CONSTRAINT FK_GUARDERIA_INTEGRANTES_INTEGRANTE
FOREIGN KEY (ID_INTEGRANTE)
REFERENCES ALCALDIA.INTEGRANTE (ID_INTEGRANTE)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.INTEGRANTE_EMPRESA ADD CONSTRAINT FK_ADULTO_INTEGRANTE
FOREIGN KEY (ID_INTEGRANTE)
REFERENCES ALCALDIA.INTEGRANTE (ID_INTEGRANTE)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.ENFERMEDAD_INTEGRANTE ADD CONSTRAINT FK_ENFERMEDAD_INTEGRANTE_INTEGRANTE
FOREIGN KEY (ID_INTEGRANTE)
REFERENCES ALCALDIA.INTEGRANTE (ID_INTEGRANTE)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.DOCUMENTO ADD CONSTRAINT FK_DOCUMENTOS_DEPENDENCIA
FOREIGN KEY (ID_DEPENCIA)
REFERENCES ALCALDIA.DEPENDENCIA (ID_DEPENCIA)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.AREA_DEPENDENCIA ADD CONSTRAINT FK_AREA_DEPENDENCIA_DEPENDENCIA
FOREIGN KEY (ID_DEPENCIA)
REFERENCES ALCALDIA.DEPENDENCIA (ID_DEPENCIA)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.EMPLEADO ADD CONSTRAINT FK_EMPLEADO_AREA_DEPENDENCIA
FOREIGN KEY (ID_AREA_DEPENDENCIA)
REFERENCES ALCALDIA.AREA_DEPENDENCIA (ID_AREA_DEPENDENCIA)
NOT DEFERRABLE;

ALTER TABLE ALCALDIA.INFRAESTRUCTURA ADD CONSTRAINT FK_INFRAESTRUCTURA_AREA_DEPENDENCIA
FOREIGN KEY (ID_AREA_DEPENDENCIA)
REFERENCES ALCALDIA.AREA_DEPENDENCIA (ID_AREA_DEPENDENCIA)
NOT DEFERRABLE;