stages:
  - clean
  - build

clean_server:
  stage: clean
  variables:
    GIT_STRATEGY: none
  tags:
    - runner
  script:
    - sudo su - jjuanrivvera99 -c 'docker rm $(docker ps -a -q) || true'
    - sudo su - jjuanrivvera99 -c 'docker rmi $(docker images -a | grep "<none>" | awk "{print $3}") || true'

build_app:
  stage: build
  variables:
    GIT_STRATEGY: none
  dependencies:
    - clean_server
  tags:
    - runner
  before_script:
    - sudo chmod 777 -R /home/jjuanrivvera99/alcaldia/core/storage/
  script:
    - sudo su - jjuanrivvera99 -c 'docker-compose --file /home/jjuanrivvera99/alcaldia/docker-compose.yml pull'
    - sudo su - jjuanrivvera99 -c 'docker-compose --file /home/jjuanrivvera99/alcaldia/docker-compose.yml up -d'
    - sudo su - jjuanrivvera99 -c 'git -C /home/jjuanrivvera99/alcaldia checkout .'
    # - sudo su - jjuanrivvera99 -c 'git -C /home/jjuanrivvera99/alcaldia checkout master'
    - sudo su - jjuanrivvera99 -c 'git -C /home/jjuanrivvera99/alcaldia pull origin master'
    # - sudo su - jjuanrivvera99 -c 'rm /home/jjuanrivvera99/alcaldia/core/.env'
    # - sudo su - jjuanrivvera99 -c 'cp /home/jjuanrivvera99/alcaldia/core/.env.example /home/jjuanrivvera99/alcaldia/core/.env'
    - sudo su - jjuanrivvera99 -c 'docker exec laravel update'
    - sudo su - jjuanrivvera99 -c 'docker exec laravel fix'
    - sudo su - jjuanrivvera99 -c 'docker exec laravel migrate'
    - sudo su - jjuanrivvera99 -c 'docker exec laravel migrate_seed'

  after_script:
    - sudo chown jjuanrivvera99:jjuanrivvera99 -R /home/jjuanrivvera99/alcaldia
    - sudo chmod 777 -R /home/jjuanrivvera99/alcaldia/core/storage/
