version: '3.3'

services:
  web:
    container_name: laravel
    restart: always
    build:
      context: ./build
    image: jjuanrivvera99/alcaldia:sql-server
    ports:
      - 80:80
    volumes:
      - ./core:/var/www

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: EayMua75bntldbLmKhig
    ports:
      - 27017:27017
    volumes:
      - db-mongo:/data/db

  mongo_express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on: 
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: EayMua75bntldbLmKhig
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: EayMua75bntldbLmKhig
      ME_CONFIG_MONGODB_URL: mongodb://root:EayMua75bntldbLmKhig@mongo?ssl=false

volumes:
  db-mongo:
  mssql-data: