version: '3.3'

services:
  web:
    container_name: laravel
    restart: always
    build:
      context: ./build
    image: jjuanrivvera99/ubuntu-apache-php-sqlserver:mongo
    ports:
      - 80:80
    volumes:
      - ./core:/var/www

  mssql:
    container_name: sql-server
    # image: mcr.microsoft.com/mssql/server:2017-CU11-ubuntu
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: LvJi7lXq8X8H2SuRx96B
    ports:
      - 1433:1433
    volumes:
     - ./mssql/data:/var/opt/mssql

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: EayMua75bntldbLmKhig
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data:/data/db

  mongo_express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on: 
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: EayMua75bntldbLmKhig
      ME_CONFIG_MONGODB_URL: mongodb://root:EayMua75bntldbLmKhig@mongo?ssl=false